defaults: &defaults
  user_avatar_dir: '<%= Rails.root %>/public/avatars'
  photo_dir: '<%= Rails.root %>/public/photos'

development:
  <<: *defaults

test:
  <<: *defaults
  user_avatar_dir: '<%= Rails.root %>/public/test_avatars'
  photo_dir: '<%= Rails.root %>/public/test_photos'

staging:
  <<: *defaults

production:
  <<: *defaults
